<a href="https://colab.research.google.com/github/alimahatma/deeplearning-pytorch/blob/main/01_pytorch_basic_lalumutawalli.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1s1IJ73OCvpcQcOblXU45uSh8jrzAvFHW')

     |████████████████████████████████| 71kB 3.3MB/s 


In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import torch

In [ ]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [ ]:
t1.dtype

torch.float32

In [ ]:
#create variabel values VECTOR
t2 = torch.tensor([1.,2,3,4])
t2

tensor([1., 2., 3., 4.])

In [ ]:
#create variabel VALUES matrix
t3 = torch.tensor([[5.,6],
                   [7, 8],
                   [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
#create variabel values 3-D
t4 = torch.tensor([
                   [[11, 12, 13],
                    [13, 14, 15]],
                   [[15, 16, 17],
                    [17, 18, 19.]]
                   ])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [ ]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [ ]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [ ]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [ ]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

In [ ]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
y.backward()


In [ ]:
print('dy/dx', x.grad)
print('dy/dx', w.grad)
print('dy/dx', b.grad)

dy/dx None
dy/dx tensor(6.)
dy/dx tensor(3.)


In [ ]:
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
t7 = torch.cat((t3, t6))
t7

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [ ]:
t7a = torch.sin(t7)
t7a

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [ ]:
t7b = t7a.reshape(3, 2, 2)
t7b

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

In [ ]:
import numpy as np

x = np.array([[1, 2],[3, 4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [ ]:
x.dtype, y.dtype

(dtype('int64'), torch.int64)

In [ ]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-pytorch-basic-lalumutawalli')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/alimahatma/01-pytorch-basic-lalumutawalli


'https://jovian.ai/alimahatma/01-pytorch-basic-lalumutawalli'