<a href="https://colab.research.google.com/github/alimahatma/deeplearning-pytorch/blob/main/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1iyci-qhrKUMOO0PFzE_w8amzXOMGl7BQ')

# An easy way to implement Tensor and Autograd
Tensor is a data type or class that represents an array, or rather an ndimensional array because it is not limited to certain dimensions. Autograd is a package which makes it easier to perform derivative calculations (differential).

- function 1 : torch.cat
- function 2 : torch.argmax
- function 3 : torch.argsort 
- function 4
- function 5

Before we begin, let's install and import PyTorch

In [1]:
# Windows
!pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
     |████████████████████████████████| 159.3MB 84kB/s 
     |████████████████████████████████| 11.8MB 25.6MB/s 
     |████████████████████████████████| 7.6MB 5.2MB/s 
  Found existing installation: torch 1.7.0+cu101
    Uninstalling torch-1.7.0+cu101:
      Successfully uninstalled torch-1.7.0+cu101
  Found existing installation: torchvision 0.8.1+cu101
    Uninstalling torchvision-0.8.1+cu101:
      Successfully uninstalled torchvision-0.8.1+cu101


In [4]:
import torch

## Function 1 - torch.cat
The torch.cat function aims to combine the sequences contained in the dimensions.


In [7]:
# Example:
dt1 = torch.zeros(5, 5)
dt2 = torch.rand(5, 5)
torch.cat((dt1, dt2))

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.8975, 0.4097, 0.8591, 0.2205, 0.9639],
        [0.5234, 0.9814, 0.9534, 0.8293, 0.1757],
        [0.0974, 0.4533, 0.5374, 0.1785, 0.0184],
        [0.8631, 0.1585, 0.1030, 0.7617, 0.8683],
        [0.7123, 0.4344, 0.5420, 0.6313, 0.9207]])

in the example above we will understand the concept of combining two variables. The first variable is dt1 which contains 5 columns and 5 rows with a blank value dt1 = torch.zeros (5, 5). and the second variable dt2 contains 5 columns and 5 rows, each of which has a random value dt2 = torch.rand (5, 5). We will combine these two variables with the torch.cat ((dt1, dt2)) function.

## Function 2 - torch.is_nonzero
This tensor functions to reproduce True if the input filled is a single element which is not equal to zero.

In [10]:
# Example 1:

dt = torch.is_nonzero(torch.tensor([0]))
dt

False

if we enter a zero value, the return value is False

In [12]:
# Example 2:
df = torch.is_nonzero(torch.tensor([6.5]))
df

True

if we enter a value other than zero or in this case we enter the value 6.5, then the return value is True

## Function 3 - torch.linspace
The function torch.linspace () returns a one-dimensional tensor of steps equally spaced points between start and end.

Syntax: torch.linspace(start, end, steps=100, out=None)

Parameters:
start: the starting value for the set of point.
end: the ending value for the set of points
steps: the gap between each pair of adjacent points. Default: 100.
out(Tensor, optional): the output tensor

In [16]:
#example
df = torch.linspace(start=11, end=15, steps=5)
df

tensor([11., 12., 13., 14., 15.])

## Function 4 - requeres_grad
Tensor has a .requires_grad attribute which defaults to False. If.requires_grad is given the value True, then the operations that occur on the tensor will be, making it possible to carry out chain derivative operations.



In [18]:
df = torch.tensor([2,5,7,9], dtype=torch.float32)
print(df.requires_grad)

False


## Function 5 - torch.FloatTensor
The function torch.tan() provides support for the tangent function in PyTorch. It expects the input in radian form and the output is in the range [-∞, ∞]. The input type is tensor and if the input contains more than one element, element-wise tangent is computed.



In [24]:
#example:
df1 =torch.FloatTensor([1.0, -0.5, -2.1, 0.0, 0.6])
print(df)

df2 = torch.tan(df1)
print(df2)

tensor([1., 2., 3.])
tensor([ 1.5574, -0.5463,  1.7098,  0.0000,  0.6841])


In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 2 - ???

Add some explanations

In [ ]:
# Example 1 - working

Explanation about example

In [ ]:
# Example 2 - working

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 3 - ???

Add some explanations

In [ ]:
# Example 1 - working

Explanation about example

In [ ]:
# Example 2 - working

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 4 - ???

Add some explanations

In [ ]:
# Example 1 - working

Explanation about example

In [ ]:
# Example 2 - working

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 5 - ???

Add some explanations

In [ ]:
# Example 1 - working

Explanation about example

In [ ]:
# Example 2 - working

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
