<a href="https://colab.research.google.com/github/alimahatma/deeplearning-pytorch/blob/main/02_pytorch_regresi_linear_lalumutawalli.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch

In [2]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [3]:
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
w = torch.rand(2, 3, requires_grad=True)
b = torch.rand(2, requires_grad=True)
print(w)
print(b)

tensor([[0.8320, 0.2749, 0.9415],
        [0.6115, 0.2040, 0.4007]], requires_grad=True)
tensor([0.9249, 0.9341], requires_grad=True)


In [6]:
def model(x):
  return x @ w.t() + b

In [7]:
preds = model(inputs)
print(preds)

tensor([[120.5672,  76.4713],
        [161.0889, 100.1771],
        [164.7585, 104.7129],
        [132.4479,  86.9024],
        [150.6333,  90.7617]], grad_fn=<AddBackward0>)


In [8]:
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff) / diff.numel()

In [9]:
loss = mse(preds, targets)
print(loss)

tensor(3127.5020, grad_fn=<DivBackward0>)


In [12]:
loss.backward()

In [13]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [14]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(2399.9900, grad_fn=<DivBackward0>)


In [28]:
for i in range(1000):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [29]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(0.6412, grad_fn=<DivBackward0>)
